#!/bin/bash

## roll back one commit and reset the current changeset to look clean


RUN_COUNT=${1:-1}
set -eu

mkdir -p ~/.git_tools_tmp/

git log -$RUN_COUNT --pretty=%B > ~/.git_tools_tmp/last_commit_message

git reset --soft HEAD~$RUN_COUNT
git reset .
