#!/bin/bash

BRANCH=$(git branch | grep "^\*" | sed 's|^\* ||g')

REMOTE=origin
if git remote -v | grep -q fork; then
  echo "Pushing Branch to Fork: $BRANCH"
  REMOTE=fork
else
  echo "Pushing Branch to Origin: $BRANCH"
fi	
git push $REMOTE $BRANCH
