#!/bin/bash


set -eux

BRANCH=${1-}

if [ -z "$BRANCH" ]; then
  BRANCH=$(git branch | grep "^\*" | sed 's|^\* ||g')
fi
END_BRANCH=${2-$BRANCH}

function push_branch() {
  local branchName=${1-}
  if git remote -v | grep -q fork; then
    echo "Pushing Branch to Fork: $branchName"
    REMOTE=fork
  else
    REMOTE=origin
    echo "Pushing Branch to Origin: $branchName"
  fi	
  git push $REMOTE "$branchName"
}

push_branch "$BRANCH" 
