#!/bin/bash

BRANCH=$(git branch | grep "^\*" | sed 's|^.* ||g')
if [ "$BRANCH" == "master" ]; then
  if ! (git remote -v | grep -q fork); then
    echo "Warning: Pushing to a master that is NOT A CLONE"
    read -p "Type exactly 'yes' if you wish to proceed: " -n 3 -r
    if [[ $REPLY = "yes" ]]; then
      echo ""
      echo "Okay, let's do this!"
      echo ""
    else
      echo "Aborting"
      exit -1
    fi
  fi
fi

echo "FORCE Pushing Branch: $BRANCH"
git push fork -f $BRANCH
