#!/bin/bash

set -eu

git status &> /dev/null || (echo "Not in a git repository" && exit 1)

if (git status | grep -q "modified:"); then
  echo "You have unstaged changes, cannot update"
  exit 2 
fi

git pull --rebase origin master

