#!/bin/bash

file=$1
branch=$2

function usage() {
  echo "Usage: $0 [file] [branch]"
  exit 1
}

if [ -z "$branch" ]; then
  echo "Error: Missing args, require 2 args"
  usage
fi

TEMP_FILE=$(mktemp)

cp $file $TEMP_FILE
git checkout $branch
mkdir -p "$(dirname $file)"
mv $TEMP_FILE $file
rm $TEMP_FILE

echo "Moved file: $(basename $file) to branch: $branch"



