#!/bin/bash

BRANCH=$1
shift
echo $@
echo $#

set -eux

function usage() {
  echo "usage: $0 [FILE_TO_MOVE] [BRANCH]"
  exit 1
}


if [ "$#" = 0 ]; then
  usage
  exit 1
fi


TEMP_FOLDER=$(mktemp -d)
#trap "rm -rf $TEMP_FOLDER" EXIT

for i in "$@"; do
  if [ ! -f "$i" ]; then
    echo "Error, not a file: $i"
  fi
done

cp $@ $TEMP_FOLDER/
git checkout "$BRANCH"

for i in "$@"; do
  TARGET_FOLDER=$(dirname "$i")
  FILE_NAME=$(basename "$i")
  mkdir -p "$TARGET_FOLDER"
  mv "$TEMP_FOLDER/$FILE_NAME" "$TARGET_FOLDER/$FILE_NAME"
done

