#!/bin/bash

# Use this to commit all current files with a 'wip' commit comment.

COMMENT=$@

if [ -z "$COMMENT" ]; then
  COMMENT="wip"
else
  COMMENT="$COMMENT"
fi

git add .
git commit . -m "$COMMENT"

